=== SonyaEr/parser/target/classes/ua/silentium/entity/vouchers/VoucherList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://silentium.ua/entity/vouchers"
	xmlns:smv="http://silentium.ua/entity/vouchers"
	elementFormDefault="qualified">

	<xsd:element name="VoucherList">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element minOccurs="1" maxOccurs="unbounded"
					name="Voucher" type="smv:Voucher" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="Voucher_count">
		<xsd:restriction base="xsd:int">
			<xsd:minExclusive value="0" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Amount">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="8" />
			<xsd:fractionDigits value="2" />
			<xsd:minInclusive value="0" />
			<xsd:maxInclusive value="99999999" />
		</xsd:restriction>
	</xsd:simpleType>


	<xsd:simpleType name="Status_voucher">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Booked" />
			<xsd:enumeration value="Waiting for" />
			<xsd:enumeration value="Confirmed" />
			<xsd:enumeration value="In the process" />
			<xsd:enumeration value="Completed" />
			<xsd:enumeration value="Annulled" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Priority">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="High-priority" />
			<xsd:enumeration value="low-priority" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="Contact_manager">
		<xsd:all>
			<xsd:element name="voucher_email" type="smv:Email" />
			<xsd:element name="voucher_tel_num" type="smv:Tel_num" />
		</xsd:all>
	</xsd:complexType>
	<xsd:complexType name="Voucher">
		<xsd:complexContent>
			<xsd:extension base="smv:Entity">
				<xsd:sequence>
					<xsd:element maxOccurs="1" minOccurs="1"
						name="voucher_count" type="smv:Voucher_count" />
					<xsd:element maxOccurs="1" minOccurs="1" name="amount"
						type="smv:Amount" />
					<xsd:element maxOccurs="1" minOccurs="1" name="Person"
						type="smv:Person" />
					<xsd:element maxOccurs="1" minOccurs="1" name="Order"
						type="smv:Order" />
					<xsd:element maxOccurs="1" minOccurs="1"
						name="voucher_date" type="xsd:dateTime" />
					<xsd:element maxOccurs="1" minOccurs="1"
						name="date_updated_voucher" type="xsd:dateTime" />
					<xsd:element maxOccurs="1" minOccurs="1"
						name="status_voucher" type="smv:Status_voucher" />
					<xsd:element maxOccurs="1" minOccurs="1"
						name="voucher_contact" type="smv:Contact_manager" />
				</xsd:sequence>
				<xsd:attribute name="priority" type="smv:Priority"
					use="optional" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:simpleType name="Order_count">
		<xsd:restriction base="xsd:int">
			<xsd:minExclusive value="0" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Status_order">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Waiting for" />
			<xsd:enumeration value="Confirmed" />
			<xsd:enumeration value="Annulled" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="Contact">
		<xsd:choice>
			<xsd:element name="order_email" type="smv:Email" />
			<xsd:element name="order_tel_num" type="smv:Tel_num" />
		</xsd:choice>
	</xsd:complexType>


	<xsd:complexType name="Order">
		<xsd:complexContent>
			<xsd:extension base="smv:Entity">
				<xsd:sequence>
					<xsd:element maxOccurs="1" minOccurs="1"
						name="order_count" type="smv:Order_count" />
					<xsd:element maxOccurs="1" minOccurs="1"
						name="Tour_date" type="smv:Tour_date" />
					<xsd:element maxOccurs="1" minOccurs="1" name="Person"
						type="smv:Person" />
					<xsd:element maxOccurs="1" minOccurs="1"
						name="order_date" type="xsd:dateTime" />
					<xsd:element maxOccurs="1" minOccurs="1"
						name="date_updated_order" type="xsd:dateTime" />
					<xsd:element maxOccurs="1" minOccurs="1"
						name="status_order" type="smv:Status_order" />
					<xsd:element maxOccurs="1" minOccurs="1"
						name="order_contact" type="smv:Contact" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:simpleType name="Price">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="7" />
			<xsd:fractionDigits value="2" />
			<xsd:minInclusive value="0" />
			<xsd:maxInclusive value="99999" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="Tour_date">
		<xsd:complexContent>
			<xsd:extension base="smv:Entity">
				<xsd:sequence>
					<xsd:element minOccurs="1" maxOccurs="1"
						name="date_arrival" type="xsd:dateTime" />
					<xsd:element minOccurs="1" maxOccurs="1" name="price"
						type="smv:Price" />
					<xsd:element minOccurs="0" maxOccurs="1"
						name="tour_date_name" type="xsd:string" />
					<xsd:element name="Tour" type="smv:Tour" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:simpleType name="Type_food">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="All inclusive" />
			<xsd:enumeration value="Breakfast" />
			<xsd:enumeration value="Breakfast and dinner" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Type_transport">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Bus" />
			<xsd:enumeration value="Airpale" />
			<xsd:enumeration value="Cruise ship" />
			<xsd:enumeration value="Foot" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="Type_tour">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Excursion" />
			<xsd:enumeration value="Gastro tour" />
			<xsd:enumeration value="Rest day" />
			<xsd:enumeration value="Cruise" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="Tour">
		<xsd:complexContent>
			<xsd:extension base="smv:Entity">
				<xsd:sequence>
					<xsd:element maxOccurs="1" minOccurs="1"
						name="tour_name" type="xsd:string" />
					<xsd:element maxOccurs="1" minOccurs="1"
						name="tour_description" type="xsd:string" />
					<xsd:element maxOccurs="1" minOccurs="1"
						name="quantity_night" type="xsd:nonNegativeInteger" />
					<xsd:element maxOccurs="1" minOccurs="1"
						name="tour_operator" type="xsd:string" />
					<xsd:element maxOccurs="1" minOccurs="1"
						name="type_food" type="smv:Type_food" />
					<xsd:element maxOccurs="1" minOccurs="1"
						name="type_transport" type="smv:Type_transport" />
					<xsd:element maxOccurs="1" minOccurs="1"
						name="type_tour" type="smv:Type_tour" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>

	</xsd:complexType>
	<xsd:simpleType name="Email">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="5" />
			<xsd:maxLength value="254" />
			<xsd:pattern
				value="[_\-a-zA-Z0-9\.\+]+@[a-zA-Z0-9]+\.[^@]+" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Tel_num">
		<xsd:restriction base="xsd:string">
			<xsd:length value="12" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Role">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Admin" />
			<xsd:enumeration value="Manager" />
			<xsd:enumeration value="Client" />
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Person">
		<xsd:complexContent>
			<xsd:extension base="smv:Entity">
				<xsd:sequence>
					<xsd:element minOccurs="1" maxOccurs="1" name="name"
						type="xsd:string" />
					<xsd:element minOccurs="1" maxOccurs="1" name="surname"
						type="xsd:string" />
					<xsd:element minOccurs="0" maxOccurs="1"
						name="patronymic" type="xsd:string" />
					<xsd:element minOccurs="0" maxOccurs="1" name="email"
						type="smv:Email" />
					<xsd:element minOccurs="1" maxOccurs="1" name="tel_num"
						type="smv:Tel_num" />
					<xsd:element minOccurs="1" maxOccurs="1" name="address"
						type="xsd:string" />
					<xsd:element minOccurs="1" maxOccurs="1"
						name="birth_date" type="xsd:date" />
					<xsd:element minOccurs="1" maxOccurs="1"
						name="document" type="xsd:string" />
					<xsd:element minOccurs="1" maxOccurs="1" name="role"
						type="smv:Role" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="Entity">
		<xsd:attribute name="id" type="smv:Id" use="required" />
	</xsd:complexType>
	<xsd:simpleType name="Id">
		<xsd:restriction base="xsd:int">
			<xsd:minInclusive value="0" />
			<xsd:maxExclusive value="999999" />
			<xsd:pattern value="[0-9]*" />
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== SonyaEr/parser/voucherlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./vouchers.xsl"?>
<smv:VoucherList xmlns:sm="http://silentium.ua/entity"
	xmlns:smv="http://silentium.ua/entity/vouchers"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://silentium.ua/entity/vouchers voucherlist.xsd ">
	<smv:Voucher id="1" priority ="High-priority">
		<smv:voucher_count>1</smv:voucher_count>
		<smv:amount>150</smv:amount>
		<smv:Person id="1">
			<smv:name>София</smv:name>
			<smv:surname>Ерошенко</smv:surname>
			<smv:email>adm@gmail.com</smv:email>
			<smv:tel_num>380970996773</smv:tel_num>
			<smv:address>г.Харьков, Победы просп., 1</smv:address>
			<smv:birth_date>2001-01-01</smv:birth_date>
			<smv:document>паспорт № 82091568</smv:document>
			<smv:role>Admin</smv:role>
		</smv:Person>
		<smv:Order id="1">
			<smv:order_count>1</smv:order_count>
			<smv:Tour_date id="1">
				<smv:date_arrival>2021-12-31T12:00:00</smv:date_arrival>
				<smv:price>150.00</smv:price>
				<smv:Tour id="1">
					<smv:tour_name>Вокруг Швейцарии </smv:tour_name>
					<smv:tour_description>Незабываемые каникулы в Альпах</smv:tour_description>
					<smv:quantity_night>4</smv:quantity_night>
					<smv:tour_operator>TEZ Tour</smv:tour_operator>
					<smv:type_food>All inclusive</smv:type_food>
					<smv:type_transport>Bus</smv:type_transport>
					<smv:type_tour>Excursion</smv:type_tour>
				</smv:Tour>
			</smv:Tour_date>
			<smv:Person id="2">
				<smv:name>Анастасия</smv:name>
				<smv:surname>Романова</smv:surname>
				<smv:patronymic>Юрьевна</smv:patronymic>
				<smv:email>client_nastya@gmail.com</smv:email>
				<smv:tel_num>380970663582</smv:tel_num>
				<smv:address>г.Харьков, Гагарина просп., 1 </smv:address>
				<smv:birth_date>2001-06-01</smv:birth_date>
				<smv:document>паспорт № 82091566</smv:document>
				<smv:role>Client</smv:role>
			</smv:Person>
			<smv:order_date>2021-10-25T09:00:00</smv:order_date>
			<smv:date_updated_order>2021-10-26T15:00:00</smv:date_updated_order>
			<smv:status_order>Confirmed</smv:status_order>
			<smv:order_contact>
				<smv:order_email>client_nastya@gmail.com</smv:order_email>
			</smv:order_contact>
		</smv:Order>
		<smv:voucher_date>2021-10-27T15:00:00</smv:voucher_date>
		<smv:date_updated_voucher>2021-10-27T17:00:00</smv:date_updated_voucher>
		<smv:status_voucher>In the process</smv:status_voucher>
		<smv:voucher_contact>
			<smv:voucher_email>sofia.eroshenko@gmail.com</smv:voucher_email>
			<smv:voucher_tel_num>380970996773</smv:voucher_tel_num>
		</smv:voucher_contact>
	</smv:Voucher>


	<smv:Voucher id="2">
		<smv:voucher_count>2</smv:voucher_count>
		<smv:amount>600</smv:amount>
		<smv:Person id="3">
			<smv:name>Марк</smv:name>
			<smv:surname>Демьяненко</smv:surname>
			<smv:email>mark_m@gmail.com</smv:email>
			<smv:tel_num>380975596773</smv:tel_num>
			<smv:address>г.Харьков, Победы просп., 48</smv:address>
			<smv:birth_date>2001-08-01</smv:birth_date>
			<smv:document>паспорт № 82066568</smv:document>
			<smv:role>Manager</smv:role>
		</smv:Person>
		<smv:Order id="3">
			<smv:order_count>2</smv:order_count>
			<smv:Tour_date id="2">
				<smv:date_arrival>2022-01-31T12:00:00</smv:date_arrival>
				<smv:price>300.00</smv:price>
				<smv:Tour id="2">
					<smv:tour_name>Польша и Чехия </smv:tour_name>
					<smv:tour_description>Быстрый отдых</smv:tour_description>
					<smv:quantity_night>6</smv:quantity_night>
					<smv:tour_operator>Accord Tour</smv:tour_operator>
					<smv:type_food>Breakfast</smv:type_food>
					<smv:type_transport>Bus</smv:type_transport>
					<smv:type_tour>Gastro tour</smv:type_tour>
				</smv:Tour>
			</smv:Tour_date>
			<smv:Person id="5">
				<smv:name>Алексей</smv:name>
				<smv:surname>Петров</smv:surname>
				<smv:patronymic>Сергеевич</smv:patronymic>
				<smv:email>client_ale@gmail.com</smv:email>
				<smv:tel_num>380975346582</smv:tel_num>
				<smv:address>г.Харьков, Киевский просп., 5 </smv:address>
				<smv:birth_date>2002-08-01</smv:birth_date>
				<smv:document>паспорт № 82771566</smv:document>
				<smv:role>Client</smv:role>
			</smv:Person>
			<smv:order_date>2021-11-02T16:30:00</smv:order_date>
			<smv:date_updated_order>2021-11-03T12:30:00</smv:date_updated_order>
			<smv:status_order>Confirmed</smv:status_order>
			<smv:order_contact>
				<smv:order_email>client_ale@gmail.com</smv:order_email>
			</smv:order_contact>
		</smv:Order>
		<smv:voucher_date>2021-11-03T12:30:00</smv:voucher_date>
		<smv:date_updated_voucher>2021-11-03T15:30:00</smv:date_updated_voucher>
		<smv:status_voucher>Booked</smv:status_voucher>
		<smv:voucher_contact>
			<smv:voucher_email>mark_m@gmail.com</smv:voucher_email>
			<smv:voucher_tel_num>380975596773</smv:voucher_tel_num>
		</smv:voucher_contact>
	</smv:Voucher>
</smv:VoucherList>

=== SonyaEr/parser/voucherlist.dom.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<VoucherList xmlns="http://silentium.ua/entity/vouchers" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://silentium.ua/entity/vouchers VoucherList.xsd">
    <Voucher id="1" priority="High-priority">
        <voucher_count>1</voucher_count>
        <amount>150</amount>
        <Person id="1">
            <name>София</name>
            <surname>Ерошенко</surname>
            <email>adm@gmail.com</email>
            <tel_num>380970996773</tel_num>
            <address>г.Харьков, Победы просп., 1</address>
            <birth_date>2001-01-01</birth_date>
            <document>паспорт № 82091568</document>
            <role>Admin</role>
        </Person>
        <Order id="1">
            <order_count>1</order_count>
            <Tour_date id="1">
                <date_arrival>2021-12-31T12:00:00</date_arrival>
                <price>150.00</price>
                <Tour id="1">
                    <tour_name>Вокруг Швейцарии </tour_name>
                    <tour_description>Незабываемые каникулы в Альпах</tour_description>
                    <quantity_night>4</quantity_night>
                    <tour_operator>TEZ Tour</tour_operator>
                    <type_food>All inclusive</type_food>
                    <type_transport>Bus</type_transport>
                    <type_tour>Excursion</type_tour>
                </Tour>
            </Tour_date>
            <Person id="2">
                <name>Анастасия</name>
                <surname>Романова</surname>
                <patronymic>Юрьевна</patronymic>
                <email>client_nastya@gmail.com</email>
                <tel_num>380970663582</tel_num>
                <address>г.Харьков, Гагарина просп., 1 </address>
                <birth_date>2001-06-01</birth_date>
                <document>паспорт № 82091566</document>
                <role>Client</role>
            </Person>
            <order_date>2021-10-25T09:00:00</order_date>
            <date_updated_order>2021-10-26T15:00:00</date_updated_order>
            <status_order>Confirmed</status_order>
            <order_contact>
                <order_email>client_nastya@gmail.com</order_email>
            </order_contact>
        </Order>
        <voucher_date>2021-10-27T15:00:00</voucher_date>
        <date_updated_voucher>2021-10-27T17:00:00</date_updated_voucher>
        <status_voucher>In the process</status_voucher>
        <voucher_contact>
            <voucher_email>sofia.eroshenko@gmail.com</voucher_email>
            <voucher_tel_num>380970996773</voucher_tel_num>
        </voucher_contact>
    </Voucher>
    <Voucher id="2">
        <voucher_count>2</voucher_count>
        <amount>600</amount>
        <Person id="3">
            <name>Марк</name>
            <surname>Демьяненко</surname>
            <email>mark_m@gmail.com</email>
            <tel_num>380975596773</tel_num>
            <address>г.Харьков, Победы просп., 48</address>
            <birth_date>2001-08-01</birth_date>
            <document>паспорт № 82066568</document>
            <role>Manager</role>
        </Person>
        <Order id="3">
            <order_count>2</order_count>
            <Tour_date id="2">
                <date_arrival>2022-01-31T12:00:00</date_arrival>
                <price>300.00</price>
                <Tour id="2">
                    <tour_name>Польша и Чехия </tour_name>
                    <tour_description>Быстрый отдых</tour_description>
                    <quantity_night>6</quantity_night>
                    <tour_operator>Accord Tour</tour_operator>
                    <type_food>Breakfast</type_food>
                    <type_transport>Bus</type_transport>
                    <type_tour>Gastro tour</type_tour>
                </Tour>
            </Tour_date>
            <Person id="5">
                <name>Алексей</name>
                <surname>Петров</surname>
                <patronymic>Сергеевич</patronymic>
                <email>client_ale@gmail.com</email>
                <tel_num>380975346582</tel_num>
                <address>г.Харьков, Киевский просп., 5 </address>
                <birth_date>2002-08-01</birth_date>
                <document>паспорт № 82771566</document>
                <role>Client</role>
            </Person>
            <order_date>2021-11-02T16:30:00</order_date>
            <date_updated_order>2021-11-03T12:30:00</date_updated_order>
            <status_order>Confirmed</status_order>
            <order_contact>
                <order_email>client_ale@gmail.com</order_email>
            </order_contact>
        </Order>
        <voucher_date>2021-11-03T12:30:00</voucher_date>
        <date_updated_voucher>2021-11-03T15:30:00</date_updated_voucher>
        <status_voucher>Booked</status_voucher>
        <voucher_contact>
            <voucher_email>mark_m@gmail.com</voucher_email>
            <voucher_tel_num>380975596773</voucher_tel_num>
        </voucher_contact>
    </Voucher>
</VoucherList>
